### ISSUE TITLE
"Unhandled rejection TypeError: Cannot read property 'language' of undefined"

### ISSUE THREAD

**Issue by shane-tomlinson** [mozilla/fxa-auth-mailer#192]
I saw this when looking at /var/log/fxa-auth-mailer.err on stomlinson.dev.lcip.org

```
Unhandled rejection TypeError: Cannot read property 'language' of undefined
    at Mailer.localize (/data/fxa-auth-mailer/mailer.js:143:27)
    at Mailer.send (/data/fxa-auth-mailer/mailer.js:152:26)
    at Mailer.verificationReminderEmail (/data/fxa-auth-mailer/mailer.js:479:17)
    at db.account.then.log.debug.err (/data/fxa-auth-mailer/lib/verification-reminders.js:31:22)
    at tryCatcher (/data/fxa-auth-mailer/node_modules/bluebird/js/main/util.js:26:23)
    at Promise._settlePromiseFromHandler (/data/fxa-auth-mailer/node_modules/bluebird/js/main/promise.js:503:31)
    at Promise._settlePromiseAt (/data/fxa-auth-mailer/node_modules/bluebird/js/main/promise.js:577:18)
    at Promise._settlePromises (/data/fxa-auth-mailer/node_modules/bluebird/js/main/promise.js:693:14)
    at Async._drainQueue (/data/fxa-auth-mailer/node_modules/bluebird/js/main/async.js:123:16)
    at Async._drainQueues (/data/fxa-auth-mailer/node_modules/bluebird/js/main/async.js:133:10)
    at Async.drainQueues (/data/fxa-auth-mailer/node_modules/bluebird/js/main/async.js:15:14)
    at process._tickDomainCallback (node.js:502:13)
```

cc @vladikoff

**Comment by philbooth** [comment]
This was for verification reminders.

**Comment by jrgm** [comment]
Actually, this fix is unneeded if the translator module was correctly initialized with a defaultLanguage - https://github.com/mozilla/fxa-auth-mailer/blob/master/bin/server.js#L24

**Comment by vladikoff** [comment]
@jrgm even if there is a default language with a set of languages this might still return `undefined`:

https://github.com/mozilla/fxa-auth-mailer/blob/master/translator.js#L44

which it did in my testing

**Comment by jrgm** [comment]
But `defaultLanguage` itself is `undefined` because no value is passed in from `bin/server.js`

**Comment by vladikoff** [comment]
@jrgm ah, well spotted!
