### ISSUE TITLE
[train-35][prod] 500 errors due to change in defaultLanguage

### ISSUE THREAD

**Issue by jrgm** [mozilla/fxa-auth-mailer#39]
With train-35 going to prod, there were ~60 500 errors in a 20 minute window before DNS was switched back to train-34 for fxa-auth-server. It was a little confusing at first seemed all errors were from Android. 

```
TypeError: Cannot call method 'gettext' of undefined 
at Mailer.verifyEmail (/data/fxa-auth-server/node_modules/fxa-auth-mailer/mailer.js:73:27) 
at Mailer.mailer.sendVerifyCode (/data/fxa-auth-server/mailer.js:21:25) 
at customs.check.then.then.then.then.then.done.account (/data/fxa-auth-server/routes/account.js:164:24) 
at HandleCallback (/data/fxa-auth-server/node_modules/p-promise/p.js:506:8) 
at Then (/data/fxa-auth-server/node_modules/p-promise/p.js:493:5) 
at Object.flush [as _onImmediate] (/data/fxa-auth-server/node_modules/p-promise/p.js:204:4) 
at processImmediate [as _immediateCallback] (timers.js:354:15)
```

At any rate, this boils down to this line:
https://github.com/mozilla/fxa-auth-mailer/blob/master/translator.js#L43
where a default of `en-US` is listed, while the fxa-content-server-l10n switched from a default of `en-US` to `en` in this release. Simply changing the line above to say `en` fixes this problem (of course it would be better if we injected the defaultLanguage from fxa-auth-server into this module, and put in a regression test).

Simple STR, is to configure your browser to use some language we don't support, e.g., `haw` for Hawaiian, and try to create an account.

**Comment by jrgm** [comment]
Draft of a fix at https://github.com/mozilla/fxa-auth-mailer/compare/master...jrgm:fix-l10n-aargh

**Comment by shane-tomlinson** [comment]
@jrgm already has a PR for this.

**Comment by jrgm** [comment]
So fixed in https://github.com/mozilla/fxa-auth-mailer/pull/40
